#!/bin/bash
# Suspende el dispositivo temporalmente
IP="192.168.1.9"
MAC="2a:c6:3d:f3:2a:b3"
echo "Suspendiendo $IP..."
echo 0207 | sudo -S iptables -C INPUT -s $IP -j DROP 2>/dev/null
if [ $? -eq 0 ]; then
    echo "⚠️ Ya está suspendido"
    exit 0
fi
echo 0207 | sudo -S iptables -A INPUT -s $IP -j DROP 2>/dev/null
echo 0207 | sudo -S iptables -A OUTPUT -d $IP -j DROP 2>/dev/null
echo "✅ Dispositivo suspendido. Para desbloquear: desbloquear"
